### ISSUE TITLE
Current CAHC's selinux-policy is from 7.2 but everything else is 7.3

### ISSUE THREAD

**Issue by petervo** [CentOS/sig-atomic-buildscripts#191]
On 

```
centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.1060 (2016-12-02 15:22:23)
        Commit: 6f9faa916eca6fe332fe8d4e2273186ab5d6fb08600c85db3c3d15b9cff47aa4
        OSName: centos-atomic-host

libselinux-utils-2.5-6.el7.x86_64
libselinux-2.5-6.el7.x86_64
selinux-policy-3.13.1-63.atomic.el7.7.noarch
libselinux-python-2.5-6.el7.x86_64
docker-selinux-1.10.3-46.el7.14.x86_64
selinux-policy-targeted-3.13.1-63.atomic.el7.7.noarch
NetworkManager-1.4.0-12.el7.x86_64
NetworkManager-libnm-1.4.0-12.el7.x86_64
```

Seeing a lot of these selinux errors.

```
Error: type=1400 audit(1480703043.439:4): avc:  denied  { create } for  pid=713 comm="NetworkManager" name="resolv.conf.X7B2RY" scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file
```

**Comment by cgwalters** [comment]
I bet this is fallout from us shipping an older selinux policy from https://github.com/CentOS/sig-atomic-buildscripts/issues/178

We really need to rebase fully on 7.3 content - it's waiting on CentOS right now.

**Comment by cgwalters** [comment]
@jasonbrooks Anything we can do to help this along?  When again is CR going to become stable and the extras/rhelah-rebuild repos be rebuilt?

**Comment by jasonbrooks** [comment]
Short of building the stuff ourselves, I don't know what we can do to speed it up.

We can remove the CR from the json for now. Actually, I'm having trouble recalling the benefit of using CR. Once the 7.3-based centos comes out, CR will empty out, because its contents just become regular centos. 

I think from time to time having CR gets us updated pkgs a bit early, that's what 120ea429da8f9faed87f05829a7ae8cec6fca8bb from a year ago says, but I can't think of specific examples...

**Comment by cgwalters** [comment]
When will CR be stable?

**Comment by cgwalters** [comment]
And when will the CentOS Core SIG rebuild the extras and rhelah-rebuild repos?

**Comment by jasonbrooks** [comment]
This is always one of those "when it's ready" things. I don't have any more visibility into it than that.

**Comment by jlebon** [comment]
This looks fixed now.

**Comment by zoobab** [comment]
I still have this issue on CentOS Linux release 7.5.1804 (Core), any idea how I can fix it?

**Comment by suthernfriend** [comment]
+1
